<a href="https://colab.research.google.com/github/Sumit11S/Workshop-0/blob/main/workshop0(AI_L6).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise on Functions:

# Task - 1: Create a Python program that converts between different units of measurement.

In [ ]:
def convert_units():
    """
    Converts between different units of measurement.

    Conversion types supported:
    - Length: meters ↔ feet
    - Weight: kilograms ↔ pounds
    - Volume: liters ↔ gallons

    Returns:
        float: Converted value
    """

    try:
        print("Choose Conversion Type:")
        print("1. Length")
        print("2. Weight")
        print("3. Volume")

        choice = input("Enter option (1-3): ")

        value = float(input("Enter value to convert: "))

        if choice == "1":
            print("1. Meters to Feet")
            print("2. Feet to Meters")
            sub = input("Choose conversion: ")

            if sub == "1":
                result = value * 3.28084
                print("Result:", result, "ft")
            elif sub == "2":
                result = value / 3.28084
                print("Result:", result, "m")
            else:
                print("Invalid option")

        elif choice == "2":
            print("1. Kilograms to Pounds")
            print("2. Pounds to Kilograms")
            sub = input("Choose conversion: ")

            if sub == "1":
                result = value * 2.20462
                print("Result:", result, "lbs")
            elif sub == "2":
                result = value / 2.20462
                print("Result:", result, "kg")
            else:
                print("Invalid option")

        elif choice == "3":
            print("1. Liters to Gallons")
            print("2. Gallons to Liters")
            sub = input("Choose conversion: ")

            if sub == "1":
                result = value * 0.264172
                print("Result:", result, "gal")
            elif sub == "2":
                result = value / 0.264172
                print("Result:", result, "L")
            else:
                print("Invalid option")

        else:
            print("Unsupported conversion type")

    except ValueError:
        print("Invalid input! Please enter numeric values.")

convert_units()

Choose Conversion Type:
1. Length
2. Weight
3. Volume
Enter option (1-3): 2
Enter value to convert: 120
1. Kilograms to Pounds
2. Pounds to Kilograms
Choose conversion: 2
Result: 54.43114913227677 kg


# Task - 2: Create a Python program that performs various mathematical operations on a list of numbers.

In [ ]:
def find_sum(numbers):
    """Returns the sum of a list of numbers."""
    return sum(numbers)

def find_average(numbers):
    """Returns the average of numbers."""
    return sum(numbers) / len(numbers)

def find_max(numbers):
    """Returns the maximum value."""
    return max(numbers)

def find_min(numbers):
    """Returns the minimum value."""
    return min(numbers)


try:
    nums = input("Enter numbers separated by space: ")
    numbers = [float(x) for x in nums.split()]

    if len(numbers) == 0:
        raise ValueError("Empty list")

    print("Choose Operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    op = input("Enter choice: ")

    if op == "1":
        print("Sum:", find_sum(numbers))
    elif op == "2":
        print("Average:", find_average(numbers))
    elif op == "3":
        print("Maximum:", find_max(numbers))
    elif op == "4":
        print("Minimum:", find_min(numbers))
    else:
        print("Invalid option")

except ValueError:
    print("Invalid input!")

Enter numbers separated by space: 10 7 10 2 3 6 
Choose Operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter choice: 2
Average: 6.333333333333333


# Exercise on List Manipulation:

# Extract Every Other Element: Write a Python function that extracts every other element from a list, starting from the first element.

In [2]:
def extract_every_other(numbers:list)->list:
  result =[]
  count =0
  size = len(numbers)
  while count < size:

    result.append(numbers[count])
    count +=2
  return result

numbers = [1,2,3,4,5,6,7,8,9,10]
print(extract_every_other(numbers))


[1, 3, 5, 7, 9]


# Slice a Sublist:

In [3]:
def get_sublist(lst:list, start:int, end:int) ->list:
  if start < 0 or end >= len(lst):
    raise ValueError("Invalid start or end index")
  return lst[start:end+1]

numbers = [1,2,4,5,6,7,8,9]
try:
  print(get_sublist(numbers, 2, 5))
except ValueError as e:
  print(e)

[4, 5, 6, 7]


# Reverse a List Using Slicing: Write a Python function that reverses a list using slicing.

In [4]:
def reverse_list(lst:list)->list:
  # Using slicing to reverse the list
  return lst[::-1]

num = [1,2,4,5]
print(reverse_list(num))

[5, 4, 2, 1]


# Remove the First and Last Elements: Write a Python function that removes the first and last elements of a list and returns the resulting sublist.

In [5]:
def remove_first_last(lst:list)->list:
  lst.pop(0)
  lst.pop(len(lst)-1)
  return lst

numbers = [1,2,3,4,5,6]
print(remove_first_last(numbers))

[2, 3, 4, 5]


# Get the First n Elements: Write a Python function that extracts the first n elements from a list.

In [6]:
def get_first_n(n:int, lst:list)->list:
  return lst[:n]

numbers = [1,2,3,4,5]
print(get_first_n(3, numbers))


[1, 2, 3]


# Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.

In [7]:
def get_last_n(lst:list, n:int)->list:
  return lst[-n:]

numbers = [1,2,3,4,5]
print(get_last_n(numbers, 3))

[3, 4, 5]


# Extract Elements in Reverse Order:
# Write a Python function that extracts a list of elements in reverse order starting from the second-to-last element and skipping one element in between.

In [8]:
def reverse_skip(lst: list) -> list:
  if len(lst) < 2:
      return []
  return lst[len(lst) - 2 :: -2]

# Example usage:
numbers = [1, 2, 3, 4, 5, 6]
print(f"Original list: {numbers}")
print(f"Extracted elements in reverse order: {reverse_skip(numbers)}")

Original list: [1, 2, 3, 4, 5, 6]
Extracted elements in reverse order: [5, 3, 1]


# 4.3 Exercise on Nested List:
# 1. Flatten a Nested List:
# Write a Python function that takes a nested list and flattens it into a single list, where all the elements are in a single dimension.

In [11]:
def flatten(lst:list) ->list:
  flat = [item for sublist in lst for item in sublist]
  return flat

input = [[1, 2], [3, 4], [5]]
print(flatten(input))

[1, 2, 3, 4, 5]


# 2. Accessing Nested List Elements:
# Write a Python function that extracts a specific element from a nested list given its indices.


In [12]:
def access_nested_element(lst:list, indices:list)->int:
  x, y = indices[0], indices[1]
  return lst[x][y]

input = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indexes = [1,2]
print(access_nested_element(input,indexes))

6


# Sum of All Elements in a Nested List:
# Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

In [13]:
def sum_nested(lst:list)->int:
  total = 0
  for element in lst:
    if isinstance(element, list):
      total += sum_nested(element)
    elif isinstance(element, (int, float)):
      total += element
  return total

input = [[1, 2], [3, [4, 5]], 6]
print(sum_nested(input))

21


# Remove Specific Element from a Nested List:
# Write a Python function that removes all occurrences of a specific element from a nested list.

In [14]:
def remove_element(lst:list, elem:int)->list:
  result = []
  for item in lst:
    if isinstance(item, list):
      new_sublist = [x for x in item if x != elem]
      result.append(new_sublist)
    elif item != elem:
      result.append(item)
  return result

input_user_example = [[1, 2], [3, 2], [4, 5]]
print(f"Input: {input_user_example}, Element to remove: 2, Output: {remove_element(input_user_example, 2)}")


Input: [[1, 2], [3, 2], [4, 5]], Element to remove: 2, Output: [[1], [3], [4, 5]]


# 5. Find the Maximum Element in a Nested List:
# Write a Python function that finds the maximum element in a nested list (regardless of depth).

In [15]:
def find_max(lst):
    stack = list(lst)
    max_val = float('-inf')

    while stack:
        item = stack.pop()
        if isinstance(item, list):
            stack.extend(item)
        else:
            if item > max_val:
                max_val = item
    return max_val

input_data = [[1, 2], [3, [4, 5]], 6]
print(find_max(input_data))

6


# 6. Count Occurrences of an Element in a Nested List:
# Write a Python function that counts how many times a specific element appears in a nested list.

In [16]:
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1  # Found a match
    return count

input_data = [[1, 2], [3, [4, 5]], 6]
print(count_occurrences(input_data, 3))

1


# 7. Flatten a List of Lists of Lists:
# Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

In [17]:
def deep_flatten(lst):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

input_data = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print(deep_flatten(input_data))

[1, 2, 3, 4, 5, 6, 7, 8]


# Nested List Average:
# Write a Python function that calculates the average of all elements in a nested list.

In [18]:
def average_nested(lst):
    total = 0
    count = 0
    for item in lst:
        if isinstance(item, list):
            sub_total, sub_count = average_nested(item)
            total += sub_total
            count += sub_count
        else:
            total += item
            count += 1
    return total, count
total, count = average_nested([[1, 2], [3, 4], [5, 6]])
avg = total / count
print(avg)

3.5


# 10 To - Do - NumPy

#10.1 Basic Vector and Matrix Operation with Numpy.
# Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [19]:
import numpy as np
empty_arr = np.empty((2,2))
print("Empty: \n",empty_arr)

all_1s_arr = np.ones((4,2))
print("All ones: \n",all_1s_arr)

new_arr = np.full((2,2), 5)
print("New: \n",new_arr)

zeroes_arr = np.zeros_like(new_arr)
print("Zeroes: \n",zeroes_arr)

ones_arr = np.ones_like(new_arr)
print("Ones: \n",ones_arr)

Empty: 
 [[7.65102989e-316 0.00000000e+000]
 [4.94065646e-324 6.58492732e-310]]
All ones: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
New: 
 [[5 5]
 [5 5]]
Zeroes: 
 [[0 0]
 [0 0]]
Ones: 
 [[1 1]
 [1 1]]


# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [20]:
import numpy as np

first_arr = np.arange(10,50)
print("1. Array ranging from 10 to 45: \n",first_arr)

second_arr = np.arange(0,9).reshape(3,3)
print("2. 3x3 matrix ranging from 0 - 8 \n",second_arr)

third_arr = np.eye(3)
print("3. 3x3 identity matrix: \n",third_arr)

fourth_arr = np.random.rand(30)
fourth_arr_mean = np.mean(fourth_arr)
print("4. Random array of size 30: \n",fourth_arr)
print("Mean of the array: \n",fourth_arr_mean)

fifth_arr = np.random.rand(10,10)
fifth_arr_max = np.max(fifth_arr)
fifth_arr_min = np.min(fifth_arr)
print("5. 10x10 array with random values: \n",fifth_arr)
print("Max value of the array: \n",fifth_arr_max)
print("Min value of the array: \n",fifth_arr_min)

sixth_arr = np.zeros(10)
sixth_arr[4] = 1
print("6. Zero array of size 10 with 5th element as 1: \n",sixth_arr)

#7. Reverse a array
arr = [1,2,0,0,4,0]
seventh_arr = np.array(arr)
seventh_arr = seventh_arr[::-1]
print("7. Reversed array: \n",seventh_arr)

eight_arr = np.ones((5,5))
eight_arr[1:-1,1:-1] = 0
print("8. 2d array with 1 on border and 0 inside: \n",eight_arr)

nine_arr = np.zeros((8,8))
nine_arr[1::2,::2] = 1
nine_arr[::2,1::2] = 1
print("9. 8x8 matrix with checkerboard pattern: \n",nine_arr)



1. Array ranging from 10 to 45: 
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
2. 3x3 matrix ranging from 0 - 8 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
3. 3x3 identity matrix: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
4. Random array of size 30: 
 [0.14470312 0.94129956 0.74208334 0.04365239 0.25619614 0.39298333
 0.08180166 0.73014849 0.81083676 0.70184464 0.78709015 0.31201736
 0.45119487 0.92644703 0.54084135 0.94284038 0.32244656 0.17620249
 0.97024686 0.15901478 0.32600178 0.03433625 0.84806324 0.43623533
 0.37540509 0.04997225 0.46307072 0.7045371  0.19296318 0.84934061]
Mean of the array: 
 0.4904605594396247
5. 10x10 array with random values: 
 [[0.53366253 0.54931163 0.6189176  0.59479829 0.22110791 0.30129687
  0.60535164 0.65466219 0.96918322 0.20023126]
 [0.40672899 0.94658697 0.88860941 0.61683138 0.92326542 0.08988972
  0.63297275 0.8950856  0.67191925 0.24053148]
 [0.0587861  0.42498118 0.77773485 0.1295534

# Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [21]:
import numpy as np

# given arrays
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

# 1. Add two arrays
print("1. Addition of x and y:")
print(x + y)

# 2. Subtract two arrays
print("\n2. Subtraction of x and y:")
print(x - y)

# 3. Multiply array with integer
print("\n3. Multiply x with 3:")
print(x * 3)

# 4. Square of each element
print("\n4. Square of elements of x:")
print(x ** 2)

# 5. Dot products
print("\n5. Dot Products:")

print("v · w =")
print(np.dot(v,w))

print("\nx · v =")
print(np.dot(x,v))

print("\nx · y =")
print(np.dot(x,y))

# 6. Concatenation
print("\n6. Concatenate x and y along rows:")
print(np.concatenate((x,y), axis=0))

print("\nConcatenate v and w along column:")
print(np.column_stack((v,w)))

# 7. Concatenate x and v
print("\n7. Trying to concatenate x and v:")

try:
    print(np.concatenate((x,v)))
except ValueError as e:
    print("Error:", e)
    print("Reason: x is a 2D array and v is a 1D array, so their dimensions do not match.")

# Correct way
print("\nCorrect way by reshaping v:")
v2 = v.reshape(1,2)
print(np.concatenate((x,v2), axis=0))

1. Addition of x and y:
[[ 6  8]
 [10 13]]

2. Subtraction of x and y:
[[-4 -4]
 [-4 -3]]

3. Multiply x with 3:
[[ 3  6]
 [ 9 15]]

4. Square of elements of x:
[[ 1  4]
 [ 9 25]]

5. Dot Products:
v · w =
219

x · v =
[29 77]

x · y =
[[19 22]
 [50 58]]

6. Concatenate x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w along column:
[[ 9 11]
 [10 12]]

7. Trying to concatenate x and v:
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Reason: x is a 2D array and v is a 1D array, so their dimensions do not match.

Correct way by reshaping v:
[[ 1  2]
 [ 3  5]
 [ 9 10]]


# Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)
T = BTAT
.
• Solve the following system of Linear equation using Inverse Methods.
2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9
{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function of Numpy}

In [23]:
import numpy as np

A = np.array([[3,4], [7,8]])
B = np.array([[5,3], [2,1]])

#1. A.A-1 = I
a_inv = np.linalg.inv(A)
identity_matrix = np.eye(2)
result = np.dot(A, a_inv)
isProven = np.allclose(result, identity_matrix)
print(f"1. A.A-1 = I: {isProven}")

#2. AB != BA
ab = np.dot(A,B)
ba = np.dot(B,A)
print(f"2. AB != BA: {not np.array_equal(ab, ba)}")

#3. (AB)T = Bt At
ab_transpose = np.transpose(ab)
aT = np.transpose(A)
bT = np.transpose(B)
bT_aT = np.dot(bT, aT)
print(f"3. (AB)T = Bt At: {np.array_equal(ab_transpose, bT_aT)}")

1. A.A-1 = I: True
2. AB != BA: True
3. (AB)T = Bt At: True


In [24]:
import numpy as np

A = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]
])

B = np.array([-1, -3, 9])

# Calculate the inverse of A
A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)

print("The values of [x, y, z] are:")
print(X)

The values of [x, y, z] are:
[ 2.  1. -2.]


# 10.2 Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:
1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.


In [25]:
import numpy as np
import time

size = 1_000_000

### 1. Using Python Lists
list_a = list(range(size))
list_b = list(range(size))

start_time = time.time()
# Element-wise addition using a list comprehension
list_result = [list_a[i] + list_b[i] for i in range(size)]
list_time = time.time() - start_time

print(f"Python List Addition Time: {list_time:.5f} seconds")


### 2. Using NumPy Arrays
array_a = np.arange(size)
array_b = np.arange(size)

start_time = time.time()
# Element-wise addition using NumPy's vectorized operation
array_result = array_a + array_b
numpy_time = time.time() - start_time

print(f"NumPy Array Addition Time:  {numpy_time:.5f} seconds")

# Calculate the speedup
print(f"\nNumPy is {list_time / numpy_time:.2f}x faster than Python lists!")

Python List Addition Time: 0.12168 seconds
NumPy Array Addition Time:  0.00516 seconds

NumPy is 23.58x faster than Python lists!


# 2. Element-wise Multiplication
• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [26]:
import numpy as np
import time

size = 1_000_000

list_a = list(range(size))
list_b = list(range(size))

start_time = time.time()
list_result = [list_a[i] * list_b[i] for i in range(size)]
list_multi_time = time.time() - start_time

print(f"Python List Multiplication Time: {list_multi_time:.5f} seconds")


array_a = np.arange(size)
array_b = np.arange(size)

start_time = time.time()
array_result = array_a * array_b
numpy_multi_time = time.time() - start_time

print(f"NumPy Array Multiplication Time:  {numpy_multi_time:.5f} seconds")

# Calculate the speedup
speedup = list_multi_time / numpy_multi_time
print(f"\nNumPy is {speedup:.2f}x faster at multiplication!")

Python List Multiplication Time: 0.12190 seconds
NumPy Array Multiplication Time:  0.00463 seconds

NumPy is 26.32x faster at multiplication!


# 3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [27]:
import numpy as np
import time

size = 1_000_000

list_a = list(range(size))
list_b = list(range(size))

start_time = time.time()
dot_product_list = sum(a * b for a, b in zip(list_a, list_b))
list_dot_time = time.time() - start_time

print(f"Python List Dot Product Time: {list_dot_time:.5f} seconds")

array_a = np.arange(size, dtype=np.int64)
array_b = np.arange(size, dtype=np.int64)

start_time = time.time()
dot_product_array = np.dot(array_a, array_b)
numpy_dot_time = time.time() - start_time

print(f"NumPy Array Dot Product Time:  {numpy_dot_time:.5f} seconds")

speedup = list_dot_time / numpy_dot_time
print(f"\nNumPy is {speedup:.2f}x faster at dot product!")

Python List Dot Product Time: 0.09154 seconds
NumPy Array Dot Product Time:  0.00220 seconds

NumPy is 41.70x faster at dot product!


# Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.
• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [28]:
import numpy as np
import time

size = 1000

list_a = [[i for i in range(size)] for j in range(size)]
list_b = [[i for i in range(size)] for j in range(size)]
list_result = [[0 for _ in range(size)] for _ in range(size)]

start_time = time.time()
for i in range(size):
    for j in range(size):
        for k in range(size):
            list_result[i][j] += list_a[i][k] * list_b[k][j]
list_time = time.time() - start_time

print(f"Python List Matrix Multiplication Time: {list_time:.5f} seconds")

# 2. Using NumPy Arrays
array_a = np.ones((size, size))
array_b = np.ones((size, size))

start_time = time.time()
array_result = np.dot(array_a, array_b) # or array_a @ array_b
numpy_time = time.time() - start_time

print(f"NumPy Array Matrix Multiplication Time:  {numpy_time:.5f} seconds")

speedup = list_time / numpy_time
print(f"\nNumPy is {speedup:.2f}x faster at matrix multiplication!")

Python List Matrix Multiplication Time: 382.67871 seconds
NumPy Array Matrix Multiplication Time:  0.06509 seconds

NumPy is 5879.08x faster at matrix multiplication!
